### ISSUE TITLE
Consistently use Nullable{T} in Data.getfield, Data.getcolumn

### ISSUE THREAD

**Issue by quinnj** [JuliaData/DataStreams.jl#19]
Currently `Data.getfield{T}(source, ::Type{T}, row, col)` returns a `Nullable{T}`. This follows traditional database design where types are given as `T` and nullability is assumed "by default". This is a natural approach, yet precludes the ability to actually return a non-null value from `Data.getfield` or even worse, `Data.getcolumn`.

I propose a change so that:
```
Data.getfield{T}(source, ::Type{T}, row, col) => T
Data.getfield{T}(source, ::Type{Nullable{T}}, row, col) => Nullable{T}

Data.getcolumn{T}(source, ::Type{T}, col) => Vector{T}
Data.getcolumn{T}(source, ::Type{Nullable{T}}, col) => NullableVector{T}
```
Luckily, the ecosystem is young enough that it's not a devastatingly breaking change.

My one gripe, however, is the onerous-ness of, for example, having to type out:
```julia
CSV.Source(file; types=[Nullable{Int}, Nullable{Date}, Nullable{Float64}, Nullable{Int}])
```
when I want to manually specify the types.

I'd appreciate any feedback on the above proposal, along with ideas around if we should have and what should a convenient short-hand be for specifying Nullable types. `T?` or `?T`? Would either of those be possible? Or maybe some kind of macro form like `@?T`?

@StefanKarpinski @JeffBezanson @davidagold @johnmyleswhite @nalimilan @yeesian @simonbyrne @davidanthoff

**Comment by nalimilan** [comment]
I've been advocating the `T?`syntax for a long time too.

Though in the particular case of `CSV.Source`, we could also imagine a `nullable=true` keyword argument which would automatically wrap the passed types inside `Nullable`. You'd set it to `false` when you don't want to allow missing values.

**Comment by JeffBezanson** [comment]
Yes, please! A boolean `nullable` keyword arg sounds good; it could even default to true if people want. Passing `nullable=false` would be much easier than my current approach of manually looping over the vectors and unwrapping them :)

**Comment by quinnj** [comment]
Alrighty, just pushed a first pass to master of `DataStreams`, `CSV`, and `SQLite`. Will work on `Feather` and `ODBC` next. Surprisingly not as tricky a change as I was expecting, but I'd appreciate some kicking of the tires if anyone is able to poke around.

**Comment by davidanthoff** [comment]
Excellent, Query.jl now deals correctly with that.

**Comment by quinnj** [comment]
Great, definitely let me know if you run into any issues. I just re-tagged DataStreams, CSV, and SQLite, as well as brought Feather up to speed with all the recent changes. Looks like there's currently a bug for 0.4 that I'm tracking down, but other than that, everything looks pretty clean. My plan is to try and finish ODBC by the end of the week.

**Comment by davidanthoff** [comment]
Cool. I should actually try Query with some other sources than just CSV... I think it should just work, but I'll add some tests to make sure.

Also, I have to think how one can collect results from a Query into a DataStreams sink, that would also be cool...

**Comment by quinnj** [comment]
Closing since this has been fully implemented now. I'm in the process of re-tagging everything now.

**Comment by quinnj** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6210

**Comment by davidanthoff** [comment]
Actually, I don't really understand this design change. Why not just have ``Data.getfield{T}(source, ::Type{T}, row, col)`` return something of type ``T``?

And if you have a data source that has a column that can have nullables, you call that with ``Nullable{T}`` as the argument for ``T``?

**Comment by quinnj** [comment]
Uh........that's what I did. That was the change.

**Comment by quinnj** [comment]
Before you could only ever do `Data.getfield{T}(source, ::Type{T}, row, col) => Nullable{T}`, but now there are two versions of `Data.getfield` for regular `T` and one for `Nullable{T}`

**Comment by davidanthoff** [comment]
Are both of these methods expected to work for any column? Say, if I have a source that has not a single column that is nullable, am I still expected to implement ``Data.getfield{T}(source, ::Type{Nullable{T}}, row, col)``?

**Comment by quinnj** [comment]
Yes, because there might be a case where a `Sink` may *require* Nullable only. But that case would be fairly trivial because you could just do
```julia
Data.getfield{T}(source, ::Type{Nullable{T}}, row, col) = Nullable{T}(Data.getfield(source, T, row, col)
```

**Comment by davidanthoff** [comment]
Couldn't we make the interface simpler by saying that if a sink wants to wrap ``T`` in a ``Nullable`` it has to do that itself? Essentially, wouldn't the interface be a lot simpler if there was just one version that has a type parameter ``T``, and the contract is that for a given column you are only allowed to call that with the type that you get from the schema for that column.

**Comment by quinnj** [comment]
Sorry, I'm not following what you're suggesting.

**Comment by davidanthoff** [comment]
I don't understand why a source has to provide a method that wraps a value in a ``Nullable``, even if the source data is not in a ``Nullable``. That seems an unnecessary complication of the interface contract. I understand that sinks might need to wrap things in a ``Nullable``, but I don't understand why that needs to be part of the contract between sources and sinks. Sinks could just wrap things in a ``Nullable`` if the need it, and that way the contract between sinks and sources would be smaller and simpler.

**Comment by nalimilan** [comment]
If defining it manually sounds too annoying, the definition @quinnj gave above could be provided by default as a fallback.
