### ISSUE TITLE
field-to-column index mapping for Data.Schema

### ISSUE THREAD

**Issue by davidagold** [JuliaData/DataStreams.jl#20]
I'm working on an interface between DataStreams and my querying package. For that purpose, it would be nice to be able easily procure a mapping from fields (column names) to the position of the column in the schema. In other words, I'd like to be able to do something like

```julia
src = CSV.Source("iris.csv")
schema = src.schema
types = schema.types
idx = index(src.schema)
j_sepal_length = idx["sepal_length"]
Data.getfield(src, types[j_sepal_length], row, j_sepal_length)
```

Does that seem reasonable? Is there a way to do that already?

EDIT: I realize that one can just do

```julia
function index(schema::Data.Schema)
    idx = Dict{String, Int}()
    for (j, field) in enumerate(schema.header)
        idx[field] = j
    end
    return idx
end
```

But it may be nice to have this functionality as a part of the Data interface and perhaps be stored in the schema itself.

**Comment by quinnj** [comment]
Yeah, this seems like something useful. I wonder if it's worth storing the index directly.

**Comment by davidagold** [comment]
I think in contexts where you'd like to be able to refer to parts of, say, an iterator based on the `Data.getfield` interface you would end up using a mapping from column names to indices (i.e., `index` as above) rather frequently. In that case, storing the index in a `Data.Schema` would make sense, and could generally serve as an explicit encoding of the canonical ordering of columns in the schema.

**Comment by quinnj** [comment]
Oh yeah, I did this. Forgot to mention it in a commit, but you can now do `Data.Schema()["col_name"]` and it returns the column index #. It actually came in handy for the new `transforms` function feature allowing the user to apply a function to a specific column either by name or number.
