### ISSUE TITLE
Interaction of sinks with Query

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataStreams.jl#21]
I've got an experimental version of Query work with DataStream sinks, so one can e.g. do something like this:
````julia
s = @from i in df begin
    @where i.age>30.
    @select i
    @collect Query.DataStreamSource
end
Feather.write("filename.feather", s)
````
So essentially the query will return a DataStream source (``s``), and that can then be passed to a sink. This all works, but I find the user experience not ideal, I would much prefer something like:
````julia
s = @from i in df begin
    @where i.age>30.
    @select i
    @collect Feather.file("filename.feather")
end
````
It might be that ``@collect`` is also not ideal for that case, i.e. maybe it should be ``@append``, but that is more of a detail.

My main question: is there a way to construct a "partial" sink. I.e. ``Feather.file("filename.feather")`` would create an instance of a type that holds the information of the filename of the sink, but doesn't have any schema information yet. And then there would be a second step, where one passes a source to that partial sink, and at that point the sink would copy the schema and start streaming the data etc.

**Comment by quinnj** [comment]
well, with Feather, you can already do `sink = Feather.Sink("filename.feather")` that doesn't need to know about the schema. You still need to be able to do a call like `Data.stream!(s, sink)` somewhere in the `@collect` step though.

**Comment by davidanthoff** [comment]
Ah, I think that is enough! Let me play with that for a moment. Does that also work with CSV?

**Comment by davidanthoff** [comment]
Ah, I think that is enough! Let me play with that for a moment. Does that also work with CSV?

**Comment by quinnj** [comment]
All the `Data.Sink` implementations currently support "independent" constructors like this (except ODBC for the moment). I think SQLite still requires a schema though, but I may have added an option that doesn't need that.

In your case, I think it would be worthwhile to implement your own `Query.write` or `Query.query` method, patterned after the "higher-level" functions that all the DataStream methods currently impelemnt (see [line 109 here](https://github.com/JuliaDB/SQLite.jl/blob/fcb04ba65297152e552aa449e8ef29bdf9d107b2/src/Source.jl) for example). The pattern there is to implement 4 methods like:
```julia
MyPkg.read(required_position_arg_for_source, ::Type{T}, varargs_for_sink...)
MyPkg.read(required_position_arg_for_source, sink::T)

MyPkg.read(source::MyPkg.Source, ::Type{T}, varargs_for_sink...)
MyPkg.read(source::MyPkg.Source, sink::T)
```
where `T` would be any `Data.Sink` type/implementation. You could then have your whole `@from etc...` basically construct a call like `Query.query(s, sink)` or `Query.query(s, ::Type{T}, args...)`. I.e. I'd be able to do
```julia
s = @from i in df begin
    @where i.age>30.
    @select i
    @collect Feather.Sink("filename.feather")
end
```
as well as
```julia
s = @from i in df begin
    @where i.age>30.
    @select i
    @collect SQLite.Sink db "output_table"
end
```

**Comment by davidanthoff** [comment]
Ok, perfect, this is all I needed, it works with both Feather and CSV now so that one can collect directly into the sink.

**Comment by davidanthoff** [comment]
I wrote my comment before I saw yours.

The first syntax now works exactly like that in my branch of Query :)

The second one I don't fully understand, wouldn't that just be:
````julia
s = @from i in df begin
    @where i.age>30.
    @select i
    @collect SQLite.Sink(db, "output_table")
end
````
If ``SQLite.Sink(db, "output_table")`` would return an object that works in a similiar way as say ``Feather.Sink("filename.feather")``, it would all work, I believe.

**Comment by davidanthoff** [comment]
I'm closing this, the latest version of [Query.jl](https://github.com/davidanthoff/Query.jl) supports collecting query results into a DataStreams sink.
