### ISSUE TITLE
Why not just use close instead of close!

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataStreams.jl#24]
That seems to only complicate things, `close` is well defined in base, why not use that for closing sinks?

**Comment by quinnj** [comment]
I think the reasoning is pretty sound: you're modifying the state of your argument, for which `!` has a lot of precedent. I would argue that `Base.close` should be `Base.close!`.

**Comment by davidanthoff** [comment]
Hm, I think packages should just follow the base conventions on things like that. Yes, you are more consistent there, but heck, now I need to read the manual to figure out how to close something, when I already know how to close lots of things in base. I think that just makes it more complicated for users, with no gain...

**Comment by davidanthoff** [comment]
I guess this issue is a good example of https://groups.google.com/forum/#!topic/julia-users/EOHKG1pE1uM.
