### ISSUE TITLE
Example Data Source?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaData/DataStreams.jl#32]
There don't seem to be any examples or tests for data sources. Nor does there seem to be much documentation at all. How do you go about doing this?

**Comment by quinnj** [comment]
Link to documentation with several links to examples is [here](http://juliadata.github.io/DataStreams.jl/stable/), which is in the github description as well as linked to from the README (for both stable and latest). I'm interested to hear why you thought there wasn't any documentation? Any ideas on how/where I can put those doc links to make it more obvious?

**Comment by ChrisRackauckas** [comment]
Oh, I clicked the sidebar for Sources and didn't see an example there, then checked the tests and didn't see much there. I think the examples at the top should have a subheader for examples, or move the source/sink examples to have subheaders in the source/sink sections. 

That's also my bad for trying to jump right to the `Source` part of the docs.
