### ISSUE TITLE
Source gets the sink row number not the source row number

### ISSUE THREAD

**Issue by JonathanAnderson** [JuliaData/DataStreams.jl#37]
I have a simple working example with output here: https://gist.github.com/JonathanAnderson/55a5ba2e7c83a9cd459fee1b11226d1e

but ultimately, what I observe is that if i have two Sources with 2 rows and 3 rows respectively, when `Data.streamfrom` is called on the second source in append=true, the row values range from 3 to 5 instead of 1 to 3.

**Comment by quinnj** [comment]
should be fixed on master
