### ISSUE TITLE
`append!(::NullableVector{WeakRefString}, ::NullableVector{WeakRefString})` is broken

### ISSUE THREAD

**Issue by spurll** [JuliaData/DataStreams.jl#38]
I've been running into a problem with appending `DataFrame`s that contain `WeakRefString`s (which is what you get when you read in string data with `CSV.read`):

```julia
julia> import CSV

julia> f1 = CSV.read(IOBuffer("a,b\n100,some string\n200,nice data please"))
2×2 DataFrames.DataFrame
│ Row │ a   │ b                  │
├─────┼─────┼────────────────────┤
│ 1   │ 100 │ "some string"      │
│ 2   │ 200 │ "nice data please" │

julia> f2 = CSV.read(IOBuffer("a,b\n300,boo\n400,hoo"))
2×2 DataFrames.DataFrame
│ Row │ a   │ b     │
├─────┼─────┼───────┤
│ 1   │ 300 │ "boo" │
│ 2   │ 400 │ "hoo" │

julia> append!(f1, f2)
4×2 DataFrames.DataFrame
│ Row │ a   │ b                  │
├─────┼─────┼────────────────────┤
│ 1   │ 100 │ ",some strin"      │
│ 2   │ 200 │ ",nice data pleas" │
│ 3   │ 300 │ ",bo"              │
│ 4   │ 400 │ ",ho"              │

julia> typeof(f1[:b])
NullableArrays.NullableArray{WeakRefString{UInt8},1}
```

The issue isn't constrained to `DataFrame`s (it also occurs when the `Sink` is a `DataTable`), and is due to the way `append!` is implemented for `NullableVector{WeakRefString}`. (Consequently, the bug doesn't occur if the `DataFrame`s in question are manually constructed with `String` columns instead of `WeakRefString`s.)

Here's an example that isolates the problem nicely (courtesy of @omus):

```julia
julia> using DataStreams, NullableArrays, WeakRefStrings

julia> foo_str = "foo"
"foo"

julia> bar_str = "bar"
"bar"

julia> foo_w = WeakRefString(pointer(foo_str), length(foo_str))
"foo"

julia> bar_w = WeakRefString(pointer(bar_str), length(bar_str))
"bar"

julia> a = NullableArray([foo_w])
1-element NullableArrays.NullableArray{WeakRefString{UInt8},1}:
 "foo"

julia> b = NullableArray([bar_w])
1-element NullableArrays.NullableArray{WeakRefString{UInt8},1}:
 "bar"

julia> append!(a, b)
2

julia> a
2-element NullableArrays.NullableArray{WeakRefString{UInt8},1}:
 "B"
 "B"
```

**Edit:** This example actually isn't a great one. See [comment below](https://github.com/JuliaData/DataStreams.jl/issues/38#issuecomment-321060149).

Note that the `"B"` in the result above could be any other byte, but it is always the same. Obviously the pointers are getting messed up somewhere in `append!`.

I've taken a quick glance at the code in question, but I don't have a solution yet. I'll take another look on Tuesday if no one else has it sussed by then. (Monday is a holiday in most of Canada.) There are currently zero tests for `append!(::NullableVector{WeakRefString}, ::NullableVector{WeakRefString})`, so that will need to be addressed by whomever tackles this, too. 😄 

Tested on Julia v0.5 and v0.6 on macOS Sierra:

```
Julia Version 0.6.1-pre.0
Commit dcf39a1dda (2017-06-19 13:06 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

```
Julia Version 0.5.1-pre+55
Commit 8d4ef37* (2017-02-13 09:11 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin16.4.0)
  CPU: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by spurll** [comment]
I've determined that the reason @omus's example above fails is that DataStreams.jl's definition of `append!` assumes that the `NullableVector`s in question are keeping track of the `parent` reference (which in this example, they aren't).

CSV.jl and DataFrames.jl should be taking care of that, however there still appears to be an off-by-one error, which suggests to me that there's a bug in DataStreams.jl's `append!` code. I'm trying to track that down at the moment. (Whether it turns out to be a bug here or not, I'll add some tests while I'm at it.)

**Comment by quinnj** [comment]
Thanks for your persistence here; I know it's not the prettiest/nicest code to work with. In the `jq/gangy` branch, I actually take a different approach using a `WeakRefStringArray` type directly, which manages it's own "parent" references in a much simpler way. The branches for `jq/gangy` are for DataStreams, CSV.jl, DataFrames.jl, and WeakRefStrings.jl. I've been a little bogged down working on some Base optimizations for isbits Unions to make those branches more efficient, so I'm not sure when those will all be ready to be merged in. I guess I could at least clean them up and merge them in master while waiting for updates to land in Base before doing another release.

**Comment by spurll** [comment]
I have tracked down the bug. It's not actually an issue specific to the `append!` method (although that method makes some assumptions about how the `NullableVector` and `WeakRefString`s are initialized that I'm not sure I'm comfortable with).

The source of the problem is actually in `CSV.parsefield`, which does not initialize the `WeakRefString`s it creates with the appropriate `ind`. Indeed, the *default* `ind` for `WeakRefString`s appears to be wrong! The two-argument dispatch provides an `ind` of 0, when it should be 1.

From what I can tell, the only purpose of `ind` is as a place to store the original pointer offset used to create the `WeakRefString`. For example, if you create a `WeakRefString` and pass in `pointer(obj, 13)`, you're also going to want `ind` to be set to 13. (That way, when we call `append!(::NullableVector{WeakRefString}, ::NullableVector{WeakRefString})` later, we don't lose that offset information.)

But calls to `pointer(obj, index)` aren't zero-indexed, they're one-indexed; calling `pointer(obj)` is essentially the same as calling `pointer(obj, 1)`. So `WeakRefString` defaults to `ind=0`, that could potentially cause problems with indexing if the `WeakRefString` becomes invalid and needs to be reconstructed from the original memory addresses.

So to get back to the fix to the problem illustrated with CSV.jl in the original issue: this line in CSV/parsefields.jl:
```julia
return (len == 0 || nullcheck) ? NULLSTRING : Nullable{WeakRefString{UInt8}}(WeakRefString(Ptr{UInt8}(ptr), len, ptr - start_ptr))
```
should actually read:
```julia
return (len == 0 || nullcheck) ? NULLSTRING : Nullable{WeakRefString{UInt8}}(WeakRefString(Ptr{UInt8}(ptr), len, ptr - start_ptr + 1))
```

Upon making that change, I'm getting the behaviour we expect. (And the existing CSV.jl tests still pass.)

```julia
julia> f1 = CSV.read(IOBuffer("a,b\n100,some string\n200,nice data please"))
2×2 DataFrames.DataFrame
│ Row │ a   │ b                  │
├─────┼─────┼────────────────────┤
│ 1   │ 100 │ "some string"      │
│ 2   │ 200 │ "nice data please" │

julia> f2 = CSV.read(IOBuffer("a,b\n300,boo\n400,hoo"))
2×2 DataFrames.DataFrame
│ Row │ a   │ b     │
├─────┼─────┼───────┤
│ 1   │ 300 │ "boo" │
│ 2   │ 400 │ "hoo" │

julia> append!(f1, f2)
4×2 DataFrames.DataFrame
│ Row │ a   │ b                  │
├─────┼─────┼────────────────────┤
│ 1   │ 100 │ "some string"      │
│ 2   │ 200 │ "nice data please" │
│ 3   │ 300 │ "boo"              │
│ 4   │ 400 │ "hoo"              │
```

Because this turned out to actually be an issue with CSV.jl, I'll open an issue there (and a PR to fix it). But at the very least I'll also issue a PR here to add a test or two for the `append!` method. And I'll also issue a PR to WeakRefStrings.jl to change the default `ind` value for the two-argument constructor.

**Comment by spurll** [comment]
Given that the actual cause of this issue was resolved with the CSV.jl PR (and the `parent` field will probably be going away in the near future anyway), I'm going to close this issue.
