### ISSUE TITLE
Julia 0.7 - Not handling data with missing values

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/DataStreams.jl#45]
While testing it on the nightly version,
```
CSV.read("NLS.csv")
```
gives 
```
DataStreams.Data.NullException("encountered a null value for a non-null column type on row = 23, col = 20")
```

**Comment by quinnj** [comment]
You'll have to provide more details; it sounds like your CSV column was detected as nonnull, yet a null value was encountered. Two options you can try are to do `CSV.read("NLS.csv"; rows_for_type_detect = 100)` the default is 20, so using 100 rows should improve the type detection process. Alternatively, if you know the nullable column, you can do `CSV.read("NLS.csv", types=Dict(3=>Union{Null, Float64}))`, if your nullable column was the 3rd column, for example.
