### ISSUE TITLE
Row streaming breaks on NamedTuples in 0.6 due to make_tuple in a generated function

### ISSUE THREAD

**Issue by iamed2** [JuliaData/DataStreams.jl#54]
https://github.com/JuliaData/DataStreams.jl/blob/master/src/DataStreams.jl#L523

`make_tuple` runs `eval` so it can't be called from within a generated function. I'm not sure what the best way to handle this is, but I'm willing to help if you have ideas.

**Comment by quinnj** [comment]
Sorry for the slow response here; nothing immediately jumps out at me. I'm starting another round of updates for DataStreams packages for 0.6/0.7 updates, so once I get some baseline updates, I'll see if there's anything we can do here. It may be the case that NamedTuples.jl doesn't need to eval.
