### ISSUE TITLE
Support transforms in Row streaming mode

### ISSUE THREAD

**Issue by iamed2** [JuliaData/DataStreams.jl#59]
Currently they are silently ignored. I'm not sure what the best way to handle this is given that the current NamedTuple approach assumes the type won't change.

**Comment by quinnj** [comment]
Hmmm, I'm wondering what this would gain over just doing `map(x-> #= do stuff =#, Data.rows(source))` yourself?

**Comment by iamed2** [comment]
Being able to use `Data.stream!` with a different Sink without materializing in between is important to us.

**Comment by davidanthoff** [comment]
[Query.jl](https://github.com/davidanthoff/Query.jl)'s ``@map`` should give you that, it is a lazy, streaming implementation that doesn't materialize anything.
