### ISSUE TITLE
Problem Streaming Data

### ISSUE THREAD

**Issue by RandomString123** [JuliaData/DataStreams.jl#62]
I have hooked up some of my code to the DataStreams capability to auto-create a data frame from it.  However I am getting the exception below when I try to stream the data.  All that I am streaming is three  fields with the strings "abcd" "12345" "10102017" in them.    

> ERROR: MethodError: Cannot `convert` an object of type Char to an object of type String
> This may have arisen from a call to the constructor String(...),
> since type constructors fall back to convert methods.
> Stacktrace:

>  [1] _append!(::Array{String,1}, ::Base.HasLength, ::String) at .\array.jl:678
>  [2] macro expansion at C:\Users\ME\.julia\v0.6\DataStreams\src\DataStreams.jl:547 [inlined]
>  [3] stream!(::FWF.Source{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Type{DataStreams.Data.Column}, ::DataFrames.DataFrameStream{Tuple{Array{String,1},Array{String,1},Array{String,1}}}, ::DataStreams.Data.Schema{true,Tuple{String,String,String}}, ::Int64, ::Tuple{Base.#identity,Base.#identity,Base.#identity}, ::DataStreams.Data.##15#16, ::Array{Any,1}, ::Type{Ref{(:Column1, :Column2, :Column3)}}) at
> C:\Users\ME\.julia\v0.6\DataStreams\src\DataStreams.jl:614
>  [4] #stream!#17(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Function, ::FWF.Source{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Type{DataFrames.DataFrame}) at C:\Users\ME\.julia\v0.6\DataStreams\src\DataStreams.jl:490
>  [5] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::FWF.Source{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Type{DataFrames.DataFrame}) at .\<missing>:0
>  [6] #read#9(::Bool, ::Dict{Int64,Function}, ::Bool, ::Array{Any,1}, ::Function, ::String, ::Array{Int64,1}, ::Type{T} where T) at C:\Users\ME\OneDrive\Documents\julia\FWF\src\io.jl:145
>  [7] read(::String, ::Array{Int64,1}) at C:\Users\ME\OneDrive\Documents\julia\FWF\src\io.jl:144
>  [8] eval(::Module, ::Any) at .\boot.jl:235
> 

I dumped all of the parameters that were going into the inline on 547 which is 
```
Data.streamto!(sink, $S, transforms[col](val_col), sinkrowoffset + row, col, $knownrows)
```
All of the data for the call is as follows:

> Sink: DataFrames.DataFrameStream{Tuple{Array{String,1},Array{String,1},Array{String,1}}}((String[], String[], String[]), String["Column1", "Column2", "Column3"])
> S: DataStreams.Data.Column
> transforms[col](val_col): "abcd"
> sinkrowoffset + row: 1
> col: 1
> knwonrows: Val{true}
> val_col: abcd ; type=String

I am willing to do more debugging but I need pointed in the right direction because I have run out of stack trace to look at.

**Comment by RandomString123** [comment]
I a lot more testing and I have to assume this has something to do with how I am streaming data and how data frames is accepting it.  I went through all of the data types I can pass by doing a simple one field data frame:

Float64:
```julia
val_col: 2.345 ; type=Float64
1×1 DataFrames.DataFrame
│ Row │ Column1 │
├─────┼─────────┤
│ 1   │ 2.345   │
```
Int:
```julia
val_col: 2345 ; type=Int64
1×1 DataFrames.DataFrame
│ Row │ Column1 │
├─────┼─────────┤
│ 1   │ 2345    │
```
String:
```julia
val_col: 2345 ; type=String
ERROR: MethodError: Cannot `convert` an object of type Char to an object of type String
This may have arisen from a call to the constructor String(...),
since type constructors fall back to convert methods.
```
Date:
```julia
val_col: 2017-10-10 ; type=Date
ERROR: MethodError: no method matching length(::Date)
Closest candidates are:
  length(::SimpleVector) at essentials.jl:256
  length(::Base.MethodList) at reflection.jl:558
  length(::MethodTable) at reflection.jl:634
```
Missing:
```julia
ERROR: MethodError: no method matching length(::Missings.Missing)
Closest candidates are:
  length(::SimpleVector) at essentials.jl:256
  length(::Base.MethodList) at reflection.jl:558
  length(::MethodTable) at reflection.jl:634
```

**Comment by RandomString123** [comment]
And I figured out the problem.  I had used a Data.Column method instead of a Data.Field method.  The error reporting / testing for that case seems pretty bad.  

It seems like this shouldn't be too bad to fix, in the column situation the code is expecting an Array so testing for items that are not one should be the route.

**Comment by quinnj** [comment]
Sorry you ran into problems here & the bad backtraces. Next time, feel free to post a link to the full code and I'm happy to review and help identify what's going on.
