### ISSUE TITLE
About the extension of `Base.|`

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaData/DataStreams.jl#86]
in [queryutils.jl:17](https://github.com/JuliaData/DataStreams.jl/blob/master/src/queryutils.jl#L17), it defines `|(::Type{A}, ::Type{B})` for `Base.|`. However, I have another package that did exactly the same thing. Thus whenever I load the two package, Julia warns `WARNING: Method definition |(Type{A}, Type{B}) in module X at xxx overwritten in module Y at yyy.`

Can we put that two lines into a separate package and depend on it instead?

**Comment by davidanthoff** [comment]
Isn’t that type piracy in any case?

**Comment by ylxdzsw** [comment]
Yes, but a separate package can help we pirates get along with each other better :)
